"""empty message

Revision ID: f68d04022e7f
Revises: bd6852023fc2
Create Date: 2020-01-12 15:09:40.103652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68d04022e7f'
down_revision = 'bd6852023fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
